name: "Deploy Terraform Infrastructure"

on:
  workflow_dispatch:
    inputs:
      rootFolder:
        description: 'Path to Terraform root directory'
        required: true
        default: './projectGCP' 
      tfvars:
        description: 'Path to .tfvars file (relative to rootFolder)'
        required: true
        default: 'parameters/dev-terraform.tfvars'
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'full-lifecycle-test' 
        type: choice
        options:
          - validate
          - fmt
          - plan
          - apply
          - destroy
          - full-lifecycle-test 

jobs:
  terraform-gcp-execution:
    name: "Execute Terraform Task on GCP"
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/257546161875/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-sa@testproject-488314.iam.gserviceaccount.com'

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "Terraform Init"
        run: terraform init -upgrade
        working-directory: ${{ github.event.inputs.rootFolder }}

      - name: "Run Terraform Format Check"
        if: ${{ github.event.inputs.action == 'fmt' }}
        run: terraform fmt -check
        working-directory: ${{ github.event.inputs.rootFolder }}

      - name: "Run Terraform Validate"
        if: ${{ github.event.inputs.action == 'validate' || github.event.inputs.action == 'full-lifecycle-test' }}
        run: terraform validate
        working-directory: ${{ github.event.inputs.rootFolder }}

      - name: "Run Terraform Plan"
        if: ${{ github.event.inputs.action == 'plan' || github.event.inputs.action == 'full-lifecycle-test' }}
        run: terraform plan -var-file="${{ github.event.inputs.tfvars }}"
        working-directory: ${{ github.event.inputs.rootFolder }}

      - name: "Run Terraform Apply"
        if: ${{ github.event.inputs.action == 'apply' || github.event.inputs.action == 'full-lifecycle-test' }}
        run: terraform apply -auto-approve -var-file="${{ github.event.inputs.tfvars }}"
        working-directory: ${{ github.event.inputs.rootFolder }}

      - name: "Run Terraform Destroy"
        if: ${{ always() && (github.event.inputs.action == 'destroy' || github.event.inputs.action == 'full-lifecycle-test') }}
        run: terraform destroy -auto-approve -var-file="${{ github.event.inputs.tfvars }}"
        working-directory: ${{ github.event.inputs.rootFolder }}
